{
    "name": "Vendor Import Module",
    "version": "18.0.1.0.1",
    "category": "Inventory",
    "summary": "Vendor import wizard scaffolding (TGH).",
    "author": "Numanski IT Solutions",
    "website": "https://www.numanski.nl",
    "depends": [
        "stock",
        "product",
        "purchase",
        "website_sale",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/cron.xml",
        "views/res_partner_views.xml",
        "views/vendor_import_settings_views.xml",
        "views/vendor_import_image_queue_views.xml",
        "views/vendor_import_wizard_views.xml",
        "views/vendor_import_profile_views.xml",
        "views/vendor_category_rule_views.xml",
        "views/product_brand_views.xml",
        "views/product_template_views.xml",
        "views/vendor_import_help_views.xml",
    ],
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
